### ISSUE TITLE
Fortify doesn't protect against petrification

### ISSUE THREAD

**Issue by Valmar33** [BlueFeuer/Divinity-Combat-Overhaul#1]
In the Gated Crypt in Stonegarden where you fight Qanna, opening the tomb will permanently petrify the character opening it.

Fortify says it should protect against petrification, but it doesn't.

(On that note, I'm not sure how the tier system works for blocking or applying status effects.)

**Comment by BlueFeuer** [comment]
Should be fixed as of a while ago, should have closed it then.

**Comment by Valmar33** [comment]
After testing, Fortify nor Magic Shell still don't protect against the tomb's petrification ~ still getting Fossilizing IV (8).
